--- 
title: "Guía de Métodos Estadísticos 2020"
author: "Pablo Cortes; Francisco Fernández"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: fjfernandezj/guiame2020
url: 'https://github.com/fjfernandezj/guiame2020'
description: "Guía para el desarrollo de Laboratorio de la asignatura Métodos Estadísticos"
---

# Bienvenidos {-}
La presente Guía tiene el objetivo de acompañarlos en los laboratorios de Métodos Estadísticos durante todo el presente semestre de este año. A través de esta guía tendrán acceso completo a toda la materia que veremos durante el semestre y adicionalmente podrán practicar todo lo que acá veamos.



```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```



